run:
  timeout: 5m
  tests: true

linters:
  enable:
    - bodyclose
    - errorlint
    - errcheck
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused

issues:
  exclude-use-default: false
