// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_metadata.sql

package sqlc

import (
	"context"
)

const getMetadata = `-- name: GetMetadata :one
SELECT key, value, created_at, updated_at
FROM app_metadata
WHERE key = $1
LIMIT 1
`

func (q *Queries) GetMetadata(ctx context.Context, key string) (AppMetadatum, error) {
	row := q.db.QueryRow(ctx, getMetadata, key)
	var i AppMetadatum
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMetadata = `-- name: ListMetadata :many
SELECT key, value, created_at, updated_at
FROM app_metadata
ORDER BY key
`

func (q *Queries) ListMetadata(ctx context.Context) ([]AppMetadatum, error) {
	rows, err := q.db.Query(ctx, listMetadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppMetadatum
	for rows.Next() {
		var i AppMetadatum
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMetadata = `-- name: UpsertMetadata :exec
INSERT INTO app_metadata (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value,
    updated_at = NOW()
`

type UpsertMetadataParams struct {
	Key   string
	Value string
}

func (q *Queries) UpsertMetadata(ctx context.Context, arg UpsertMetadataParams) error {
	_, err := q.db.Exec(ctx, upsertMetadata, arg.Key, arg.Value)
	return err
}
